survey_begin: 57377.197060
#survey_begin: 57800.0
survey_end: 59022.61850675

lower_declination_limit: -40.0 #degrees
upper_declination_limit: 80.0  #degrees
declination_band_width: 5

lower_redshift_limit: 0.01401
upper_redshift_limit: 0.01634
#10.0 Mpc is z = 0.00233
#20.0 Mpc is z = 0.00467
#30.0 Mpc is z = 0.00700
#40.0 Mpc is z = 0.00934
#50.0 Mpc is z = 0.01167
#60.0 Mpc is z = 0.01401
#70.0 Mpc is z = 0.01634
#80.0 Mpc is z = 0.01868
#90.0 Mpc is z = 0.02101
#100.0 Mpc is z = 0.02335
#110.0 Mpc is z = 0.02568
#120.0 Mpc is z = 0.02802
#130.0 Mpc is z = 0.03035
#140.0 Mpc is z = 0.03269
#150.0 Mpc is z = 0.03502
num_redshift_bins: 10

sample_size: 500

QC_file: 'QC/QC_all_data_kws_57308_59024_20200624_merged_daves_moving_object_database_data.dat'
QC_columns:
    qc_time: 'MJDOBS'
    qc_limits: 'MAG5SIG'
    qc_filters: 'FILTER'
    qc_ra: 'RA'
    qc_dec: 'DEC'
chipwidth: 5.46 #degrees

transient_data_file: 'transients/abs_AT2017gfo.csv'
lower_fit_time_limit: -0.25 #days
upper_fit_time_limit: 11.5  #days
polynomial_degree: 7

do_extinction: True
plot_mode: True
save_results: True
flavour_mode: True

results_directory: '500_kn_60to70Mpc'







