survey_begin: 57377.197060
survey_end: 59022.61850675

lower_declination_limit: -40.0
upper_declination_limit: 80.0

lower_redshift_limit: 0.000
upper_redshift_limit: 0.015
num_redshift_bins: 5

sample_size: 5

ATLAS_data_file: 'QC/QC_all_data_kws_57308_59024_20200624_merged_daves_moving_object_database_data.dat'

kilonova_data_file: 'kilonova/abs_AT2017gfo.csv'
lower_fit_time_limit: -0.75
upper_fit_time_limit: 11.5
polynomial_degree: 7

do_extinction: True
plot_mode: True







