survey_begin: 57377.197060
#survey_begin: 57800.0
survey_end: 59022.61850675

lower_declination_limit: -40.0
upper_declination_limit: 80.0
declination_band_width: 5

lower_redshift_limit: 0.000
upper_redshift_limit: 0.025
num_redshift_bins: 5

sample_size: 20

ATLAS_data_file: 'QC/QC_all_data_kws_57308_59024_20200624_merged_daves_moving_object_database_data.dat'

kilonova_data_file: 'transients/abs_AT2017gfo.csv'
lower_fit_time_limit: -0.25
upper_fit_time_limit: 11.5
polynomial_degree: 7

do_extinction: True
plot_mode: True
save_results: True

results_directory: 'test'







