survey_begin: 57377.197060
survey_end: 59022.61850675

lower_redshift_limit: 0.1
upper_redshift_limit: 0.5
num_redshift_bins: 5

ATLAS_data_file: 'QC/QC_all_data_kws_57308_59024_20200624_merged_daves_moving_object_database_data.dat'









